name: Test Web UI
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/web-test.yml'
      - '.github/workflows/web-deploy.yml'
      - 'moon/**'

env:
  TIPTAP_PRIVATE_REGISTRY_KEY: CjqFil0n7z4GGur+RPric21fBBeSB4R4FoNdRYOE1bQEz6AXLCoANCc+o9rLIg6Q

jobs:
  test-web-ui:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v4.0.0
      #   with:
      #     version: 9

      # - name: Get pnpm store directory
      #   shell: bash
      #   run: |
      #     echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # - uses: actions/cache@v4
      #   name: Setup pnpm cache
      #   with:
      #     path: ${{ env.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      # - run: pnpm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
      # - run: pnpm config set "//registry.tiptap.dev/:_authToken" ${{ secrets.TIPTAP_PRIVATE_REGISTRY_KEY }}

      # - name: Install dependencies
      #   working-directory: ./moon
      #   run: pnpm i --frozen-lockfile

      # - name: Run ESLint
      #   working-directory: ./moon
      #   run: pnpm run lint

      # - name: Build Next.js application
      #   working-directory: ./moon
      #   run: pnpm run build

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
      - run: pnpm config set "//registry.tiptap.dev/:_authToken" ${{ env.TIPTAP_PRIVATE_REGISTRY_KEY }}

      - name: Install dependencies
        working-directory: ./moon
        run: pnpm i --frozen-lockfile

      - name: Run ESLint
        working-directory: ./moon
        run: pnpm run lint

      - name: Build Next.js application
        working-directory: ./moon
        run: pnpm run build
